- name: Install Redis repository
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Enable Redis module
  ansible.builtin.shell: |
    yum module enable redis:remi-6.2 -y
  # The shell command should not have `-y` inside the module argument. Use `|` for multi-line commands if needed.

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present
  # Use `present` instead of `started` since `started` is for services, not packages.

- name: Update listen address in redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  # Correct the IP address and ensure this file is the correct one for Redis config.

- name: Update listen address in redis directory config
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  # Same as above, make sure the file path is correct.

- name: Start and enable Redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
  # This ensures the Redis service is started and enabled.
