      - name: Add the application user
        ansible.builtin.user:
         name: roboshop

      - name: clean old content
        ansible.builtin.file:
          path: /app
          state: absent

      - name: create app directory
        ansible.builtin.file:
          path: /app
          state: directory

      - name: download and extract application content
        ansible.builtin.unarchive:
          src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
          dest: /usr/share/nginx/html
          remote_src: yes





#
#    echo -e "\e[36m>>>>>>>>>>>>  Download Application Content  <<<<<<<<<<<<\e[0m"
#    curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log}
#    func_exit_status
#
#    echo -e "\e[36m>>>>>>>>>>>>  Extract Application Content  <<<<<<<<<<<<\e[0m"
#    cd /app
#    unzip /tmp/${component}.zip &>>${log}
#    func_exit_status
#  }
