- name: catalogue setup
  hosts: all
  become: true
  vars:
    component: catalogue
    schema: true
  tasks:
    - name: catalogue setup
      ansible.builtin.import_tasks:
          file: nodejs.yml






