- name: mysql setup
  hosts: all
  become: yes
  tasks:
    - name: configuaration yum repo for mysql
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: disable mysql default version
      ansible.builtin.shell: dnf module disable mysql -y

    - name: install mysql community server
      yum:
        name: mysql-server
        state: present

    - name: start mysql service
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: yes



    - name: set root password
      ansible.builtin.shell: mysql --host=mysql-dev.nkdevops29.online --user=root --password= RoboShop@1 < /app/schema/{{component}}.sql







